In [81]:
%matplotlib inline
import numpy as np
import pandas as pd
import matplotlib as mpl
import matplotlib.pylab as plt
dataSetIris = pd.read_csv("../data/iris.txt",delim_whitespace=True)
dataSetIris

sl   sw   pl   pw  c
0    5.1  3.5  1.4  0.2  1
1    4.9  3.0  1.4  0.2  1
2    4.7  3.2  1.3  0.2  1
3    4.6  3.1  1.5  0.2  1
4    5.0  3.6  1.4  0.2  1
5    5.4  3.9  1.7  0.4  1
6    4.6  3.4  1.4  0.3  1
7    5.0  3.4  1.5  0.2  1
8    4.4  2.9  1.4  0.2  1
9    4.9  3.1  1.5  0.1  1
10   5.4  3.7  1.5  0.2  1
11   4.8  3.4  1.6  0.2  1
12   4.8  3.0  1.4  0.1  1
13   4.3  3.0  1.1  0.1  1
14   5.8  4.0  1.2  0.2  1
15   5.7  4.4  1.5  0.4  1
16   5.4  3.9  1.3  0.4  1
17   5.1  3.5  1.4  0.3  1
18   5.7  3.8  1.7  0.3  1
19   5.1  3.8  1.5  0.3  1
20   5.4  3.4  1.7  0.2  1
21   5.1  3.7  1.5  0.4  1
22   4.6  3.6  1.0  0.2  1
23   5.1  3.3  1.7  0.5  1
24   4.8  3.4  1.9  0.2  1
25   5.0  3.0  1.6  0.2  1
26   5.0  3.4  1.6  0.4  1
27   5.2  3.5  1.5  0.2  1
28   5.2  3.4  1.4  0.2  1
29   4.7  3.2  1.6  0.2  1
..   ...  ...  ...  ... ..
120  6.9  3.2  5.7  2.3  3
121  5.6  2.8  4.9  2.0  3
122  7.7  2.8  6.7  2.0  3
123  6.3  2.7  4.9  1.8  3
124  6.7  3.3  5.7  2.1  3
125  7.2  3.2  6.0  1.8  3
126  6.2  2.8  4.8  1.8  3
127  6.1  3.0  4.9  1.8  3
128  6.4  2.8  5.6  2.1  3
129  7.2  3.0  5.8  1.6  3
130  7.4  2.8  6.1  1.9  3
131  7.9  3.8  6.4  2.0  3
132  6.4  2.8  5.6  2.2  3
133  6.3  2.8  5.1  1.5  3
134  6.1  2.6  5.6  1.4  3
135  7.7  3.0  6.1  2.3  3
136  6.3  3.4  5.6  2.4  3
137  6.4  3.1  5.5  1.8  3
138  6.0  3.0  4.8  1.8  3
139  6.9  3.1  5.4  2.1  3
140  6.7  3.1  5.6  2.4  3
141  6.9  3.1  5.1  2.3  3
142  5.8  2.7  5.1  1.9  3
143  6.8  3.2  5.9  2.3  3
144  6.7  3.3  5.7  2.5  3
145  6.7  3.0  5.2  2.3  3
146  6.3  2.5  5.0  1.9  3
147  6.5  3.0  5.2  2.0  3
148  6.2  3.4  5.4  2.3  3
149  5.9  3.0  5.1  1.8  3

[150 rows x 5 columns]

In [95]:
x = np.hstack((np.matrix(dataSetIris.sl[0:]).T, np.matrix(dataSetIris.sw[0:]).T, 
               np.matrix(dataSetIris.pl[0:]).T, np.matrix(dataSetIris.pw[0:]).T, 
               np.matrix(dataSetIris.c[0:]).T))

x

matrix([[ 5.1,  3.5,  1.4,  0.2,  1. ],
        [ 4.9,  3. ,  1.4,  0.2,  1. ],
        [ 4.7,  3.2,  1.3,  0.2,  1. ],
        [ 4.6,  3.1,  1.5,  0.2,  1. ],
        [ 5. ,  3.6,  1.4,  0.2,  1. ],
        [ 5.4,  3.9,  1.7,  0.4,  1. ],
        [ 4.6,  3.4,  1.4,  0.3,  1. ],
        [ 5. ,  3.4,  1.5,  0.2,  1. ],
        [ 4.4,  2.9,  1.4,  0.2,  1. ],
        [ 4.9,  3.1,  1.5,  0.1,  1. ],
        [ 5.4,  3.7,  1.5,  0.2,  1. ],
        [ 4.8,  3.4,  1.6,  0.2,  1. ],
        [ 4.8,  3. ,  1.4,  0.1,  1. ],
        [ 4.3,  3. ,  1.1,  0.1,  1. ],
        [ 5.8,  4. ,  1.2,  0.2,  1. ],
        [ 5.7,  4.4,  1.5,  0.4,  1. ],
        [ 5.4,  3.9,  1.3,  0.4,  1. ],
        [ 5.1,  3.5,  1.4,  0.3,  1. ],
        [ 5.7,  3.8,  1.7,  0.3,  1. ],
        [ 5.1,  3.8,  1.5,  0.3,  1. ],
        [ 5.4,  3.4,  1.7,  0.2,  1. ],
        [ 5.1,  3.7,  1.5,  0.4,  1. ],
        [ 4.6,  3.6,  1. ,  0.2,  1. ],
        [ 5.1,  3.3,  1.7,  0.5,  1. ],
        [ 4.8,  3.4,  1.9,  0.2,  1. ],


In [119]:
# Split the iris data set into two partitions.
# One will be used for training, the other for testing. - Noise will be applied into the test data.

x_dataSet = x
x_testSet = x
#x_testSet = x[50:]
#x_testSet = x_testSet[:50]

x_testSet

matrix([[ 5.1       ,  3.5       ,  1.4       ,  0.2       ,  1.        ],
        [ 4.9       ,  3.        ,  1.4       ,  0.2       ,  1.        ],
        [ 4.7       ,  3.2       ,  1.3       ,  0.2       ,  1.        ],
        [ 4.6       ,  3.1       ,  1.5       ,  0.2       ,  1.        ],
        [ 5.        ,  3.6       ,  1.4       ,  0.2       ,  1.        ],
        [ 5.4       ,  3.9       ,  1.7       ,  0.4       ,  1.        ],
        [ 4.6       ,  3.4       ,  1.4       ,  0.3       ,  1.        ],
        [ 5.        ,  3.4       ,  1.5       ,  0.2       ,  1.        ],
        [ 4.4       ,  2.9       ,  1.4       ,  0.2       ,  1.        ],
        [ 4.9       ,  3.1       ,  1.5       ,  0.1       ,  1.        ],
        [ 5.4       ,  3.7       ,  1.5       ,  0.2       ,  1.        ],
        [ 4.8       ,  3.4       ,  1.6       ,  0.2       ,  1.        ],
        [ 4.8       ,  3.        ,  1.4       ,  0.1       ,  1.        ],
        [ 4.3       ,  3.

In [120]:
for i in range(len(x_testSet)):
    temp = x_testSet[i].item(4)
    x_testSet[i] = x_testSet[i,:] + 0.1*np.random.randn(1,5)
    x_testSet[i, 4] = temp
x_testSet

matrix([[ 5.09722321,  3.58039206,  1.46121326,  0.20303405,  1.        ],
        [ 4.88531344,  2.83155815,  1.32784278,  0.23736932,  1.        ],
        [ 4.63393722,  3.22828964,  1.27535035,  0.19758982,  1.        ],
        [ 4.66125273,  3.04707598,  1.64048503,  0.1608251 ,  1.        ],
        [ 5.05781809,  3.8158087 ,  1.43162196,  0.16146385,  1.        ],
        [ 5.43183674,  3.81178447,  1.68524073,  0.4122655 ,  1.        ],
        [ 4.50245614,  3.39797194,  1.47828858,  0.39352557,  1.        ],
        [ 4.97965367,  3.56782919,  1.42587728,  0.18928822,  1.        ],
        [ 4.39971319,  2.81928242,  1.42832924,  0.15702866,  1.        ],
        [ 4.7933869 ,  3.10001638,  1.48831254,  0.12820765,  1.        ],
        [ 5.41470135,  3.59796284,  1.39755709,  0.24472338,  1.        ],
        [ 4.77173892,  3.55188611,  1.63838527,  0.33253129,  1.        ],
        [ 4.82092112,  3.12994544,  1.4705584 ,  0.26622668,  1.        ],
        [ 4.21180197,  3.

In [123]:
def findDistance(dataSet, test):
    distance = np.zeros(len(x_dataSet))
    dataSet = dataSet
    for i in range(0, len(dataSet)):
        dist = 0
        for j in range(4):
            #print j
            #print dataSet[i].item(j)
            #print test.item(j)
            #print (dataSet[i].item(j) - test.item(j))
            dist += pow((dataSet[i].item(j) - test.item(j)), 2)
            #print dist
        distance[i] = np.sqrt(dist)
    #print distance
    return distance

def findResult(vote, result, k, length):
    #print vote
    for i in range(length):
        classCounter = np.zeros(k)
        for j in range(k):
            if votes[i].item(j) == 1:
                classCounter[0] += 1
            elif votes[i][j] == 2:
                classCounter[1] += 1
            else:
                classCounter[2] += 1
        #print classCounter
        maxIndex = np.argmax(classCounter)
        #print maxIndex
        result[i] = (maxIndex + 1)
    return result

def findTruePos(result, testSet, origin):
    truePositive = 0
    for i in range(len(result)):
        if result[i] == origin:
            truePositive += 1
    return truePositive

def findFalseNeg(result, x_testSet, origin):
    falseNegative = 0
    for i in range(len(result)):
        if x_testSet[i, 4] == origin:
            if result[i] != origin:
                falseNegative += 1
    return falseNegative

def findTrueNeg(result, x_testSet, origin):
    trueNegative = 0
    for i in range(len(result)):
        if x_testSet[i, 4] != origin:
            if result[i] != origin:
                trueNegative += 1
    return trueNegative

def findFalsePos(result, x_testSet, origin):
    falsePositive = 0
    for i in range(len(result)):
        if x_testSet[i, 4] != origin:
            if result[i] == origin:
                falsePositive += 1
    return falsePositive


dist = np.zeros(len(x_dataSet))
#dist
result = np.zeros(len(x_testSet))
k = 3
votes = np.zeros([len(x_testSet), k])
#print votes

for ii in range(0, len(x_testSet)):
    dist = findDistance(x_dataSet, x_testSet[ii])
    idx = np.argpartition(dist, k)
    #print idx
    #print dist[idx[:k]]
    for jj in range(k):
        #print x_dataSet[idx[jj]].item(4)
        votes[ii][jj] = x_dataSet[idx[jj]].item(4)

findResult(votes, result, k, len(x_testSet))

#print result

#print x_testSet[:,4].T

# Find the performance metrics of classification of class 2 versus 1 and 3:
truePos = findTruePos(result, x_testSet, 2)
trueNeg = findTrueNeg(result, x_testSet, 2)
falsePos = findFalsePos(result, x_testSet, 2)
falseNeg = findFalseNeg(result, x_testSet, 2)

print('truePos = ' + repr(truePos) + ', trueNeg = ' + repr(trueNeg) + 
      ', falsePos = ' + repr(falsePos) + ', falseNeg = ' + repr(falseNeg) + '\n')

accuracy = float((truePos + trueNeg) / float(truePos + falsePos + trueNeg + falseNeg)) * 100
precision = float(truePos / float(truePos + falsePos)) * 100
recall = float(truePos / float(truePos + falseNeg)) * 100

print('accuracy = ' + repr(accuracy) + '%, precision = ' + repr(precision) + 
      '%, recall = ' + repr(recall) + '%\n')

truePos = 48, trueNeg = 99, falsePos = 1, falseNeg = 3

accuracy = 97.35099337748345%, precision = 97.95918367346938%, recall = 94.11764705882352%

