In [ ]:
Student Name: Yesim Oral


In [10]:
%matplotlib inline
import numpy as np
import pandas as pd
import matplotlib as mpl
import matplotlib.pylab as plt
import random as rand
dataSetIris = pd.read_csv("../data/iris.txt",delim_whitespace=True)
dataSetIris

sl   sw   pl   pw  c
0    5.1  3.5  1.4  0.2  1
1    4.9  3.0  1.4  0.2  1
2    4.7  3.2  1.3  0.2  1
3    4.6  3.1  1.5  0.2  1
4    5.0  3.6  1.4  0.2  1
5    5.4  3.9  1.7  0.4  1
6    4.6  3.4  1.4  0.3  1
7    5.0  3.4  1.5  0.2  1
8    4.4  2.9  1.4  0.2  1
9    4.9  3.1  1.5  0.1  1
10   5.4  3.7  1.5  0.2  1
11   4.8  3.4  1.6  0.2  1
12   4.8  3.0  1.4  0.1  1
13   4.3  3.0  1.1  0.1  1
14   5.8  4.0  1.2  0.2  1
15   5.7  4.4  1.5  0.4  1
16   5.4  3.9  1.3  0.4  1
17   5.1  3.5  1.4  0.3  1
18   5.7  3.8  1.7  0.3  1
19   5.1  3.8  1.5  0.3  1
20   5.4  3.4  1.7  0.2  1
21   5.1  3.7  1.5  0.4  1
22   4.6  3.6  1.0  0.2  1
23   5.1  3.3  1.7  0.5  1
24   4.8  3.4  1.9  0.2  1
25   5.0  3.0  1.6  0.2  1
26   5.0  3.4  1.6  0.4  1
27   5.2  3.5  1.5  0.2  1
28   5.2  3.4  1.4  0.2  1
29   4.7  3.2  1.6  0.2  1
..   ...  ...  ...  ... ..
120  6.9  3.2  5.7  2.3  3
121  5.6  2.8  4.9  2.0  3
122  7.7  2.8  6.7  2.0  3
123  6.3  2.7  4.9  1.8  3
124  6.7  3.3  5.7  2.1  3
125  7.2  3.2  6.0  1.8  3
126  6.2  2.8  4.8  1.8  3
127  6.1  3.0  4.9  1.8  3
128  6.4  2.8  5.6  2.1  3
129  7.2  3.0  5.8  1.6  3
130  7.4  2.8  6.1  1.9  3
131  7.9  3.8  6.4  2.0  3
132  6.4  2.8  5.6  2.2  3
133  6.3  2.8  5.1  1.5  3
134  6.1  2.6  5.6  1.4  3
135  7.7  3.0  6.1  2.3  3
136  6.3  3.4  5.6  2.4  3
137  6.4  3.1  5.5  1.8  3
138  6.0  3.0  4.8  1.8  3
139  6.9  3.1  5.4  2.1  3
140  6.7  3.1  5.6  2.4  3
141  6.9  3.1  5.1  2.3  3
142  5.8  2.7  5.1  1.9  3
143  6.8  3.2  5.9  2.3  3
144  6.7  3.3  5.7  2.5  3
145  6.7  3.0  5.2  2.3  3
146  6.3  2.5  5.0  1.9  3
147  6.5  3.0  5.2  2.0  3
148  6.2  3.4  5.4  2.3  3
149  5.9  3.0  5.1  1.8  3

[150 rows x 5 columns]

In [35]:
x = np.hstack((np.matrix(dataSetIris.sl[0:]).T, np.matrix(dataSetIris.sw[0:]).T, 
               np.matrix(dataSetIris.pl[0:]).T, np.matrix(dataSetIris.pw[0:]).T, 
               np.matrix(dataSetIris.c[0:]).T))

x

matrix([[ 5.1,  3.5,  1.4,  0.2,  1. ],
        [ 4.9,  3. ,  1.4,  0.2,  1. ],
        [ 4.7,  3.2,  1.3,  0.2,  1. ],
        [ 4.6,  3.1,  1.5,  0.2,  1. ],
        [ 5. ,  3.6,  1.4,  0.2,  1. ],
        [ 5.4,  3.9,  1.7,  0.4,  1. ],
        [ 4.6,  3.4,  1.4,  0.3,  1. ],
        [ 5. ,  3.4,  1.5,  0.2,  1. ],
        [ 4.4,  2.9,  1.4,  0.2,  1. ],
        [ 4.9,  3.1,  1.5,  0.1,  1. ],
        [ 5.4,  3.7,  1.5,  0.2,  1. ],
        [ 4.8,  3.4,  1.6,  0.2,  1. ],
        [ 4.8,  3. ,  1.4,  0.1,  1. ],
        [ 4.3,  3. ,  1.1,  0.1,  1. ],
        [ 5.8,  4. ,  1.2,  0.2,  1. ],
        [ 5.7,  4.4,  1.5,  0.4,  1. ],
        [ 5.4,  3.9,  1.3,  0.4,  1. ],
        [ 5.1,  3.5,  1.4,  0.3,  1. ],
        [ 5.7,  3.8,  1.7,  0.3,  1. ],
        [ 5.1,  3.8,  1.5,  0.3,  1. ],
        [ 5.4,  3.4,  1.7,  0.2,  1. ],
        [ 5.1,  3.7,  1.5,  0.4,  1. ],
        [ 4.6,  3.6,  1. ,  0.2,  1. ],
        [ 5.1,  3.3,  1.7,  0.5,  1. ],
        [ 4.8,  3.4,  1.9,  0.2,  1. ],


In [36]:
# Split the iris data set into two partitions.
# One will be used for training, the other for testing. - Noise will be applied into the test data.

np.random.shuffle(x)

x_dataSet = x[:120]
x_testSet = x[120:]

x_testSet

matrix([[ 5.7,  2.8,  4.1,  1.3,  2. ],
        [ 6.2,  2.2,  4.5,  1.5,  2. ],
        [ 6.7,  3.3,  5.7,  2.1,  3. ],
        [ 5.6,  3. ,  4.1,  1.3,  2. ],
        [ 6.6,  2.9,  4.6,  1.3,  2. ],
        [ 7. ,  3.2,  4.7,  1.4,  2. ],
        [ 6.3,  3.3,  6. ,  2.5,  3. ],
        [ 5.5,  2.5,  4. ,  1.3,  2. ],
        [ 6.5,  3. ,  5.5,  1.8,  3. ],
        [ 4.4,  2.9,  1.4,  0.2,  1. ],
        [ 7.3,  2.9,  6.3,  1.8,  3. ],
        [ 4.4,  3. ,  1.3,  0.2,  1. ],
        [ 6.3,  3.4,  5.6,  2.4,  3. ],
        [ 5. ,  2. ,  3.5,  1. ,  2. ],
        [ 6.3,  2.8,  5.1,  1.5,  3. ],
        [ 5.8,  4. ,  1.2,  0.2,  1. ],
        [ 4.9,  3. ,  1.4,  0.2,  1. ],
        [ 5.1,  3.4,  1.5,  0.2,  1. ],
        [ 5.1,  3.3,  1.7,  0.5,  1. ],
        [ 4.3,  3. ,  1.1,  0.1,  1. ],
        [ 5.8,  2.7,  3.9,  1.2,  2. ],
        [ 5.4,  3.9,  1.7,  0.4,  1. ],
        [ 7.4,  2.8,  6.1,  1.9,  3. ],
        [ 5.1,  3.8,  1.9,  0.4,  1. ],
        [ 6.7,  2.5,  5.8,  1.8,  3. ],


In [37]:
for i in range(len(x_testSet)):
    temp = x_testSet[i].item(4)
    # Acc, precision and recall metrics change with the weight of the noise
    x_testSet[i] = x_testSet[i,:] + 0.2*np.random.randn(1,5)
    x_testSet[i, 4] = temp
x_testSet

matrix([[ 5.6681297 ,  2.68643957,  4.3978908 ,  1.60934075,  2.        ],
        [ 6.06585787,  2.37481878,  4.87710497,  1.74713797,  2.        ],
        [ 6.68130982,  3.05847304,  5.87601832,  2.41863603,  3.        ],
        [ 5.64961366,  2.97891485,  4.15993503,  1.33947451,  2.        ],
        [ 7.01041415,  2.65323985,  4.66408444,  1.44381835,  2.        ],
        [ 6.93594511,  3.4033684 ,  4.56991921,  1.48176286,  2.        ],
        [ 6.12980792,  3.05369981,  5.77575289,  2.51554836,  3.        ],
        [ 5.40182913,  2.83398344,  3.93216167,  1.29335081,  2.        ],
        [ 6.21414848,  2.86784219,  5.35417052,  2.13442405,  3.        ],
        [ 4.70459466,  3.00097411,  1.02207801,  0.19304116,  1.        ],
        [ 7.34797127,  2.77085812,  6.09053771,  1.45168788,  3.        ],
        [ 5.08327913,  2.70808623,  1.18221724,  0.25278099,  1.        ],
        [ 6.36714498,  3.48082742,  5.80921639,  2.46383615,  3.        ],
        [ 4.81476489,  1.

In [38]:
def findDistance(dataSet, test):
    distance = np.zeros(len(x_dataSet))
    dataSet = dataSet
    for i in range(0, len(dataSet)):
        dist = 0
        for j in range(4):
            #print j
            #print dataSet[i].item(j)
            #print test.item(j)
            #print (dataSet[i].item(j) - test.item(j))
            dist += pow((dataSet[i].item(j) - test.item(j)), 2)
            #print dist
        distance[i] = np.sqrt(dist)
    #print distance
    return distance

def findResult(vote, result, k, length):
    #print vote
    for i in range(length):
        classCounter = np.zeros(k)
        for j in range(k):
            if votes[i].item(j) == 1:
                classCounter[0] += 1
            elif votes[i][j] == 2:
                classCounter[1] += 1
            else:
                classCounter[2] += 1
        #print classCounter
        maxIndex = np.argmax(classCounter)
        #print maxIndex
        result[i] = (maxIndex + 1)
    return result

def findTruePos(result, testSet, origin):
    truePositive = 0
    for i in range(len(result)):
        if result[i] == origin:
            truePositive += 1
    return truePositive

def findFalseNeg(result, x_testSet, origin):
    falseNegative = 0
    for i in range(len(result)):
        if x_testSet[i, 4] == origin:
            if result[i] != origin:
                falseNegative += 1
    return falseNegative

def findTrueNeg(result, x_testSet, origin):
    trueNegative = 0
    for i in range(len(result)):
        if x_testSet[i, 4] != origin:
            if result[i] != origin:
                trueNegative += 1
    return trueNegative

def findFalsePos(result, x_testSet, origin):
    falsePositive = 0
    for i in range(len(result)):
        if x_testSet[i, 4] != origin:
            if result[i] == origin:
                falsePositive += 1
    return falsePositive


dist = np.zeros(len(x_dataSet))
#dist
result = np.zeros(len(x_testSet))
k = 3
votes = np.zeros([len(x_testSet), k])
#print votes

for ii in range(0, len(x_testSet)):
    dist = findDistance(x_dataSet, x_testSet[ii])
    idx = np.argpartition(dist, k)
    #print idx
    #print dist[idx[:k]]
    for jj in range(k):
        #print x_dataSet[idx[jj]].item(4)
        votes[ii][jj] = x_dataSet[idx[jj]].item(4)

findResult(votes, result, k, len(x_testSet))

#print result

#print x_testSet[:,4].T

# Find the performance metrics of classification of class 2 versus 1 and 3:
truePos = findTruePos(result, x_testSet, 2)
trueNeg = findTrueNeg(result, x_testSet, 2)
falsePos = findFalsePos(result, x_testSet, 2)
falseNeg = findFalseNeg(result, x_testSet, 2)

print('truePos = ' + repr(truePos) + ', trueNeg = ' + repr(trueNeg) + 
      ', falsePos = ' + repr(falsePos) + ', falseNeg = ' + repr(falseNeg) + '\n')

accuracy = float((truePos + trueNeg) / float(truePos + falsePos + trueNeg + falseNeg)) * 100
precision = float(truePos / float(truePos + falsePos)) * 100
recall = float(truePos / float(truePos + falseNeg)) * 100

print('accuracy = ' + repr(accuracy) + '%, precision = ' + repr(precision) + 
      '%, recall = ' + repr(recall) + '%\n')

truePos = 11, trueNeg = 18, falsePos = 2, falseNeg = 1

accuracy = 90.625%, precision = 84.61538461538461%, recall = 91.66666666666666%

